from PyroUbot.core.plugins.pmper import *
from PyroUbot.core.plugins.lck import *
from PyroUbot.core.plugins.pler import *
from PyroUbot.core.plugins.vctls import *
from PyroUbot.core.plugins.gtb import *
from PyroUbot.core.plugins.prefix import *
from PyroUbot.core.plugins.join import *
from PyroUbot.core.plugins.crbn import *
from PyroUbot.core.plugins.prof import *
from PyroUbot.core.plugins.ip import *
from PyroUbot.core.plugins.adb import *
from PyroUbot.core.plugins.adm import *
from PyroUbot.core.plugins.alv import *
from PyroUbot.core.plugins.cpy import *
from PyroUbot.core.plugins.ctr import *
from PyroUbot.core.plugins.cvr import *
from PyroUbot.core.plugins.dbf import *
from PyroUbot.core.plugins.evl import *
from PyroUbot.core.plugins.fnt import *
from PyroUbot.core.plugins.gcs import *
from PyroUbot.core.plugins.hlp import *
from PyroUbot.core.plugins.img import *
from PyroUbot.core.plugins.ivt import *
from PyroUbot.core.plugins.kng import *
from PyroUbot.core.plugins.lmt import *
from PyroUbot.core.plugins.mmf import *
from PyroUbot.core.plugins.nts import *
from PyroUbot.core.plugins.opi import *
from PyroUbot.core.plugins.pgr import *
from PyroUbot.core.plugins.pyn import *
from PyroUbot.core.plugins.qrq import *
from PyroUbot.core.plugins.qtl import *
from PyroUbot.core.plugins.rts import *
from PyroUbot.core.plugins.sct import *
from PyroUbot.core.plugins.sid import *
from PyroUbot.core.plugins.smd import *
from PyroUbot.core.plugins.smt import *
from PyroUbot.core.plugins.spm import *
from PyroUbot.core.plugins.str import *
from PyroUbot.core.plugins.tny import *
from PyroUbot.core.plugins.tph import *
from PyroUbot.core.plugins.whs import *
from PyroUbot.core.plugins.ytp import *
from PyroUbot.core.plugins.zbs import *
from PyroUbot.core.plugins.tr import *
from PyroUbot.core.plugins.gratis import *
